spring.application.name=teste


spring.datasource.url=jdbc:mysql://localhost:3306/senai_tarde
spring.datasource.username=root
spring.datasource.password=alunolab


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
